### ISSUE TITLE
Handle docs versioning

### ISSUE THREAD

**Issue by JoelMarcey** [hhvm/user-documentation#246]
Our initial launch of the docs is HHVM 3.11. But if features are added or removed for 3.12+, we need a way for folks to see docs from either HHVM version. Maybe some side bar option to choose docs associated with a specific HHVM version.

**Comment by andrerom** [comment]
release docs for 3.11 and 3.12 is also missing, so currently even harder to figure out what is in our out.

**Comment by fredemmott** [comment]
We're not supporting multiple versions, however we now support annotations for the guides (e.g. https://docs.hhvm.com/hack/disposables/async-disposables) via blocks like this:

~~~
```yamlmeta
{
  "min-versions": {
    "HHVM": "3.24"
  },
  "experimental": true
}
```
~~~

We need something similar for generated API references.
